package com.example.oxigenplayer

object OxigenStrings {
    private val translations = mapOf(
        "ro" to mapOf(
            "settings_title" to "Setări OxigenPlayer",
            "translate_all" to "TRADU TOT (AI BACKGROUND)",
            "load_subtitles" to "ÎNCARCĂ SUBTITRAREA PT. AI",
            "translating" to "Traducere",
            "translation_settings" to "Sursă Traducere",
            "style_settings" to "Stil Subtitrare",
            "language_settings" to "Limbă Aplicație",
            "about_dev_btn" to "Despre Dezvoltator",
            "close_dialog" to "Închide",
            "translation_label" to "Traducere",
            "enable_translation_label" to "Activare Traducere",
            "translation_engine" to "Motor de traducere:",
            "source_lang" to "Limbă Sursă",
            "target_lang" to "Limbă Țintă",
            "change" to "Schimbă",
            "style_label" to "Stil",
            "font_size_label" to "Mărime",
            "language_label" to "Limbă",
            "close_btn" to "ÎNCHIDE",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Dezvoltator: OxigenForFlower",
            "done_btn" to "Gata",
            "tracks_title" to "Piste",
            "disable_subtitles" to "Dezactivează Subtitrările",
            "select_media" to "Selectează Media",
            "media_label" to "Media",
            "settings_label" to "Setări",
            "online_search" to "Căutare Online"
        ),
        "en" to mapOf(
            "settings_title" to "OxigenPlayer Settings",
            "translate_all" to "TRANSLATE ALL (AI BACKGROUND)",
            "load_subtitles" to "LOAD SUBTITLES FOR AI",
            "translating" to "Translating",
            "translation_settings" to "Translation Source",
            "style_settings" to "Subtitle Style",
            "language_settings" to "App Language",
            "about_dev_btn" to "About Developer",
            "close_dialog" to "Close",
            "translation_label" to "Translation",
            "enable_translation_label" to "Enable Translation",
            "translation_engine" to "Translation engine:",
            "source_lang" to "Source Language",
            "target_lang" to "Target Language",
            "change" to "Change",
            "style_label" to "Style",
            "font_size_label" to "Size",
            "language_label" to "Language",
            "close_btn" to "CLOSE",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Developer: OxigenForFlower",
            "done_btn" to "Done",
            "tracks_title" to "Tracks",
            "disable_subtitles" to "Disable Subtitles",
            "select_media" to "Select Media",
            "media_label" to "Media",
            "settings_label" to "Settings",
            "online_search" to "Online Search"
        ),
        "es" to mapOf(
            "settings_title" to "Ajustes de OxigenPlayer",
            "translate_all" to "TRADUCIR TODO (AI BACKGROUND)",
            "load_subtitles" to "CARGAR SUBTÍTULOS PARA IA",
            "translating" to "Traduciendo",
            "translation_settings" to "Fuente de traducción",
            "style_settings" to "Estilo de subtítulos",
            "language_settings" to "Idioma de la aplicación",
            "about_dev_btn" to "Sobre el desarrollador",
            "close_dialog" to "Cerrar",
            "translation_label" to "Traducción",
            "enable_translation_label" to "Activar traducción",
            "translation_engine" to "Motor de traducción:",
            "source_lang" to "Idioma de origen",
            "target_lang" to "Idioma de destino",
            "change" to "Cambiar",
            "style_label" to "Estilo",
            "font_size_label" to "Tamaño",
            "language_label" to "Idioma",
            "close_btn" to "CERRAR",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Desarrollador: OxigenForFlower",
            "done_btn" to "Hecho",
            "tracks_title" to "Pistas",
            "disable_subtitles" to "Desactivar subtítulos",
            "select_media" to "Seleccionar medios",
            "media_label" to "Medios",
            "settings_label" to "Ajustes",
            "online_search" to "Búsqueda en línea"
        ),
        "fr" to mapOf(
            "settings_title" to "Paramètres OxigenPlayer",
            "translate_all" to "TOUT TRADUIRE (AI BACKGROUND)",
            "load_subtitles" to "CHARGER LES SOUS-TITRES POUR L'IA",
            "translating" to "Traduction",
            "translation_settings" to "Source de traduction",
            "style_settings" to "Style de sous-titre",
            "language_settings" to "Langue de l'application",
            "about_dev_btn" to "À propos du développeur",
            "close_dialog" to "Fermer",
            "translation_label" to "Traduction",
            "enable_translation_label" to "Activer la traduction",
            "translation_engine" to "Moteur de traduction :",
            "source_lang" to "Langue source",
            "target_lang" to "Langue cible",
            "change" to "Modifier",
            "style_label" to "Style",
            "font_size_label" to "Taille",
            "language_label" to "Langue",
            "close_btn" to "FERMER",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Développeur : OxigenForFlower",
            "done_btn" to "Terminé",
            "tracks_title" to "Pistes",
            "disable_subtitles" to "Désactiver les sous-titres",
            "select_media" to "Sélectionner un média",
            "media_label" to "Média",
            "settings_label" to "Paramètres",
            "online_search" to "Recherche en ligne"
        ),
        "de" to mapOf(
            "settings_title" to "OxigenPlayer Einstellungen",
            "translate_all" to "ALLES ÜBERSETZEN (AI BACKGROUND)",
            "load_subtitles" to "UNTERTITEL FÜR KI LADEN",
            "translating" to "Übersetzen",
            "translation_settings" to "Übersetzungsquelle",
            "style_settings" to "Untertitel-Stil",
            "language_settings" to "App-Sprache",
            "about_dev_btn" to "Über den Entwickler",
            "close_dialog" to "Schließen",
            "translation_label" to "Übersetzung",
            "enable_translation_label" to "Übersetzung aktivieren",
            "translation_engine" to "Übersetzungs-Engine:",
            "source_lang" to "Quellsprache",
            "target_lang" to "Zielsprache",
            "change" to "Ändern",
            "style_label" to "Stil",
            "font_size_label" to "Größe",
            "language_label" to "Sprache",
            "close_btn" to "SCHLIESSEN",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Entwickler: OxigenForFlower",
            "done_btn" to "Fertig",
            "tracks_title" to "Spuren",
            "disable_subtitles" to "Untertitel deaktivieren",
            "select_media" to "Medien auswählen",
            "media_label" to "Medien",
            "settings_label" to "Einstellungen",
            "online_search" to "Online-Suche"
        ),
        "it" to mapOf(
            "settings_title" to "Impostazioni OxigenPlayer",
            "translate_all" to "TRADUCI TUTTO (AI BACKGROUND)",
            "load_subtitles" to "CARICA SOTTOTITOLI PER IA",
            "translating" to "Traduzione",
            "translation_settings" to "Sorgente traduzione",
            "style_settings" to "Stile sottotitoli",
            "language_settings" to "Lingua dell'app",
            "about_dev_btn" to "Informazioni sullo sviluppatore",
            "close_dialog" to "Chiudi",
            "translation_label" to "Traduzione",
            "enable_translation_label" to "Attiva traduzione",
            "translation_engine" to "Motore di traduzione:",
            "source_lang" to "Lingua di origine",
            "target_lang" to "Lingua di destinazione",
            "change" to "Cambia",
            "style_label" to "Stile",
            "font_size_label" to "Dimensione",
            "language_label" to "Lingua",
            "close_btn" to "CHIUDI",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Sviluppatore: OxigenForFlower",
            "done_btn" to "Fatto",
            "tracks_title" to "Tracce",
            "disable_subtitles" to "Disattiva sottotitoli",
            "select_media" to "Seleziona file multimediali",
            "media_label" to "Media",
            "settings_label" to "Impostazioni",
            "online_search" to "Ricerca online"
        ),
        "ru" to mapOf(
            "settings_title" to "Настройки OxigenPlayer",
            "translate_all" to "ПЕРЕВЕСТИ ВСЕ (AI BACKGROUND)",
            "load_subtitles" to "ЗАГРУЗИТЬ СУБТИТРЫ ДЛЯ ИИ",
            "translating" to "Перевод",
            "translation_settings" to "Источник перевода",
            "style_settings" to "Стиль субтитров",
            "language_settings" to "Язык приложения",
            "about_dev_btn" to "О разработчике",
            "close_dialog" to "Закрыть",
            "translation_label" to "Перевод",
            "enable_translation_label" to "Включить перевод",
            "translation_engine" to "Система перевода:",
            "source_lang" to "Исходный язык",
            "target_lang" to "Целевой язык",
            "change" to "Изменить",
            "style_label" to "Стиль",
            "font_size_label" to "Размер",
            "language_label" to "Язык",
            "close_btn" to "ЗАКРЫТЬ",
            "about_dev_title" to "Oxigen Player",
            "about_dev_text" to "Разработчик: OxigenForFlower",
            "done_btn" to "Готово",
            "tracks_title" to "Дорожки",
            "disable_subtitles" to "Отключить субтитры",
            "select_media" to "Выбрать медиа",
            "media_label" to "Медиа",
            "settings_label" to "Настройки",
            "online_search" to "Онлайн поиск"
        )
    )

    fun get(lang: String, key: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
