package com.example.oxigenplayer

object OxigenStrings {
    private val translations = mapOf(
        "ro" to mapOf(
            "settings_title" to "Setări Oxigen",
            "trans_source" to "Sursă Traducere",
            "os_auth" to "OpenSubtitles Auth",
            "sub_style" to "Stil Subtitrare",
            "app_lang" to "Limbă Aplicație",
            "about_dev" to "DESPRE DEVELOPER",
            "close" to "ÎNCHIDE",
            "done" to "GATA",
            "active_trans" to "Traducere Activă",
            "real_time" to "Traduce în timp real",
            "select_source" to "Selectează Sursa",
            "source_lang" to "Limba Sursă",
            "target_lang" to "Limba Destinație",
            "change" to "Schimbă",
            "user" to "Utilizator",
            "pass" to "Parolă",
            "logging_in" to "Se autentifică...",
            "login_success" to "Autentificare cu succes!",
            "login_failed" to "Autentificare eșuată!",
            "search_lang" to "Limbă Căutare",
            "other" to "ALTA",
            "size" to "Dimensiune",
            "text_color" to "Culoare Text",
            "bg_color" to "Fundal Text",
            "online_search" to "Căutare Subtitrări Online",
            "movie_name" to "Nume film...",
            "search" to "Caută",
            "download_error" to "Eroare la descărcare.",
            "enter_name" to "Introdu numele și apasă Caută",
            "back" to "Înapoi",
            "all" to "Ambele",
            "about_text" to "Dezvoltat de OxigenForFlower pentru o experiență multimedia superioară."
        ),
        "en" to mapOf(
            "settings_title" to "Oxigen Settings",
            "trans_source" to "Translation Source",
            "os_auth" to "OpenSubtitles Auth",
            "sub_style" to "Subtitle Style",
            "app_lang" to "App Language",
            "about_dev" to "ABOUT DEVELOPER",
            "close" to "CLOSE",
            "done" to "DONE",
            "active_trans" to "Active Translation",
            "real_time" to "Translate in real-time",
            "select_source" to "Select Source",
            "source_lang" to "Source Language",
            "target_lang" to "Target Language",
            "change" to "Change",
            "user" to "Username",
            "pass" to "Password",
            "logging_in" to "Logging in...",
            "login_success" to "Login successful!",
            "login_failed" to "Login failed!",
            "search_lang" to "Search Language",
            "other" to "OTHER",
            "size" to "Size",
            "text_color" to "Text Color",
            "bg_color" to "Text Background",
            "online_search" to "Online Subtitle Search",
            "movie_name" to "Movie name...",
            "search" to "Search",
            "download_error" to "Download error.",
            "enter_name" to "Enter name and press Search",
            "back" to "Back",
            "all" to "Both",
            "about_text" to "Developed by OxigenForFlower for a superior multimedia experience."
        ),
        "es" to mapOf(
            "settings_title" to "Ajustes Oxigen",
            "trans_source" to "Fuente de Traducción",
            "os_auth" to "OpenSubtitles Auth",
            "sub_style" to "Estilo de Subtítulos",
            "app_lang" to "Idioma de la Aplicación",
            "about_dev" to "SOBRE EL DESARROLLADOR",
            "close" to "CERRAR",
            "done" to "HECHO",
            "active_trans" to "Traducción Activa",
            "real_time" to "Traducir en tiempo real",
            "select_source" to "Seleccionar Fuente",
            "source_lang" to "Idioma de Origen",
            "target_lang" to "Idioma de Destino",
            "change" to "Cambiar",
            "user" to "Usuario",
            "pass" to "Contraseña",
            "logging_in" to "Iniciando sesión...",
            "login_success" to "¡Inicio de sesión exitoso!",
            "login_failed" to "¡Error de inicio de sesión!",
            "search_lang" to "Idioma de Búsqueda",
            "other" to "OTRO",
            "size" to "Tamaño",
            "text_color" to "Color del Texto",
            "bg_color" to "Fondo del Texto",
            "online_search" to "Búsqueda de Subtítulos en Línea",
            "movie_name" to "Nombre de la película...",
            "search" to "Buscar",
            "download_error" to "Error de descarga.",
            "enter_name" to "Ingrese el nombre y presione Buscar",
            "back" to "Atrás",
            "all" to "Ambos",
            "about_text" to "Desarrollado por OxigenForFlower para una experiencia multimedia superior."
        ),
        "fr" to mapOf(
            "settings_title" to "Paramètres Oxigen",
            "trans_source" to "Source de Traduction",
            "os_auth" to "Authentification OpenSubtitles",
            "sub_style" to "Style de Sous-titre",
            "app_lang" to "Langue de l'Application",
            "about_dev" to "À PROPOS DU DÉVELOPPEUR",
            "close" to "FERMER",
            "done" to "TERMINÉ",
            "active_trans" to "Traduction Active",
            "real_time" to "Traduire en temps réel",
            "select_source" to "Sélectionner la Source",
            "source_lang" to "Langue Source",
            "target_lang" to "Langue Cible",
            "change" to "Modifier",
            "user" to "Nom d'utilisateur",
            "pass" to "Mot de passe",
            "logging_in" to "Connexion...",
            "login_success" to "Connexion réussie !",
            "login_failed" to "Échec de la connexion !",
            "search_lang" to "Langue de Recherche",
            "other" to "AUTRE",
            "size" to "Taille",
            "text_color" to "Couleur du Texte",
            "bg_color" to "Arrière-plan du Texte",
            "online_search" to "Recherche de Sous-titres en Ligne",
            "movie_name" to "Nom du film...",
            "search" to "Rechercher",
            "download_error" to "Erreur de téléchargement.",
            "enter_name" to "Entrez le nom et appuyez sur Rechercher",
            "back" to "Retour",
            "all" to "Les deux",
            "about_text" to "Développé par OxigenForFlower pour une expérience multimédia supérieure."
        ),
        "de" to mapOf(
            "settings_title" to "Oxigen Einstellungen",
            "trans_source" to "Übersetzungsquelle",
            "os_auth" to "OpenSubtitles Auth",
            "sub_style" to "Untertitel-Stil",
            "app_lang" to "App-Sprache",
            "about_dev" to "ÜBER DEN ENTWICKLER",
            "close" to "SCHLIESSEN",
            "done" to "FERTIG",
            "active_trans" to "Aktive Übersetzung",
            "real_time" to "Echtzeit-Übersetzung",
            "select_source" to "Quelle auswählen",
            "source_lang" to "Quellsprache",
            "target_lang" to "Zielsprache",
            "change" to "Ändern",
            "user" to "Benutzername",
            "pass" to "Passwort",
            "logging_in" to "Anmeldung...",
            "login_success" to "Anmeldung erfolgreich!",
            "login_failed" to "Anmeldung fehlgeschlagen!",
            "search_lang" to "Suchsprache",
            "other" to "ANDERE",
            "size" to "Größe",
            "text_color" to "Textfarbe",
            "bg_color" to "Texthintergrund",
            "online_search" to "Online-Untertitelsuche",
            "movie_name" to "Filmname...",
            "search" to "Suchen",
            "download_error" to "Download-Fehler.",
            "enter_name" to "Name eingeben und Suchen drücken",
            "back" to "Zurück",
            "all" to "Beide",
            "about_text" to "Entwickelt von OxigenForFlower für ein erstklassiges Multimedia-Erlebnis."
        ),
        "it" to mapOf(
            "settings_title" to "Impostazioni Oxigen",
            "trans_source" to "Sorgente Traduzione",
            "os_auth" to "Autenticazione OpenSubtitles",
            "sub_style" to "Stile Sottotitoli",
            "app_lang" to "Lingua dell'App",
            "about_dev" to "INFO SVILUPPATORE",
            "close" to "CHIUDI",
            "done" to "FATTO",
            "active_trans" to "Traduzione Attiva",
            "real_time" to "Traduci in tempo reale",
            "select_source" to "Seleziona Sorgente",
            "source_lang" to "Lingua di Origine",
            "target_lang" to "Lingua di Destinazione",
            "change" to "Cambia",
            "user" to "Nome utente",
            "pass" to "Password",
            "logging_in" to "Accesso in corso...",
            "login_success" to "Accesso effettuato con successo!",
            "login_failed" to "Accesso fallito!",
            "search_lang" to "Lingua di Ricerca",
            "other" to "ALTRO",
            "size" to "Dimensione",
            "text_color" to "Colore Testo",
            "bg_color" to "Sfondo Testo",
            "online_search" to "Ricerca Sottotitoli Online",
            "movie_name" to "Nome film...",
            "search" to "Cerca",
            "download_error" to "Errore di download.",
            "enter_name" to "Inserisci il nome e premi Cerca",
            "back" to "Indietro",
            "all" to "Entrambi",
            "about_text" to "Sviluppato da OxigenForFlower per un'esperienza multimediale superiore."
        ),
        "pt" to mapOf(
            "settings_title" to "Configurações Oxigen",
            "trans_source" to "Fonte de Tradução",
            "os_auth" to "Autenticação OpenSubtitles",
            "sub_style" to "Estilo de Legenda",
            "app_lang" to "Idioma do App",
            "about_dev" to "SOBRE O DESENVOLVEDOR",
            "close" to "FECHAR",
            "done" to "CONCLUÍDO",
            "active_trans" to "Tradução Ativa",
            "real_time" to "Traduzir em tempo real",
            "select_source" to "Selecionar Fonte",
            "source_lang" to "Idioma de Origem",
            "target_lang" to "Idioma de Destino",
            "change" to "Alterar",
            "user" to "Usuário",
            "pass" to "Senha",
            "logging_in" to "Iniciando sessão...",
            "login_success" to "Sessão iniciada com sucesso!",
            "login_failed" to "Falha ao iniciar sessão!",
            "search_lang" to "Idioma de Busca",
            "other" to "OUTRO",
            "size" to "Tamanho",
            "text_color" to "Cor do Texto",
            "bg_color" to "Fundo do Texto",
            "online_search" to "Busca de Legendas Online",
            "movie_name" to "Nome do filme...",
            "search" to "Buscar",
            "download_error" to "Erro no download.",
            "enter_name" to "Digite o nome e pressione Buscar",
            "back" to "Voltar",
            "all" to "Ambos",
            "about_text" to "Desenvolvido por OxigenForFlower para uma experiência multimédia superior."
        ),
        "ru" to mapOf(
            "settings_title" to "Настройки Oxigen",
            "trans_source" to "Источник перевода",
            "os_auth" to "Авторизация OpenSubtitles",
            "sub_style" to "Стиль субтитров",
            "app_lang" to "Язык приложения",
            "about_dev" to "О РАЗРАБОТЧИКЕ",
            "close" to "ЗАКРЫТЬ",
            "done" to "ГОТОВО",
            "active_trans" to "Активный перевод",
            "real_time" to "Перевод в реальном времени",
            "select_source" to "Выберите источник",
            "source_lang" to "Исходный язык",
            "target_lang" to "Язык перевода",
            "change" to "Изменить",
            "user" to "Логин",
            "pass" to "Пароль",
            "logging_in" to "Вход...",
            "login_success" to "Успешный вход!",
            "login_failed" to "Ошибка входа!",
            "search_lang" to "Язык поиска",
            "other" to "ДРУГОЙ",
            "size" to "Размер",
            "text_color" to "Цвет текста",
            "bg_color" to "Фон текста",
            "online_search" to "Поиск субтитров онлайн",
            "movie_name" to "Название фильма...",
            "search" to "Поиск",
            "download_error" to "Ошибка загрузки.",
            "enter_name" to "Введите название и нажмите Поиск",
            "back" to "Назад",
            "all" to "Оба",
            "about_text" to "Разработано OxigenForFlower для превосходного мультимедийного опыта."
        )
    )

    fun get(lang: String, key: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
